assert.throws(ReferenceError, function() {
  f;
});
{
  function f() {  }
}
assert.throws(ReferenceError, function() {
  f;
});