assert.throws(ReferenceError, function() {
  e0
});