assert.throws(ReferenceError, function() {
  async
  identifier => {}
});