assert.throws(ReferenceError, function() {
  (function() {}({a: 0, ...unresolvableReference}));
});